server:
  port: 8001

spring:
  application:
    name: model-instance-service
  datasource:
    url: jdbc:mysql://139.199.110.213:3306/orchestrator?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root@256
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: cn.edu.xidian.modelinstance.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


