package cn.edu.xidian.modelinstance.mapper;

import cn.edu.xidian.modelinstance.entity.SysModel;
import java.util.List;

public interface SysModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_model
     *
     * @mbg.generated Sat Nov 30 15:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_model
     *
     * @mbg.generated Sat Nov 30 15:42:04 CST 2019
     */
    int insert(SysModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_model
     *
     * @mbg.generated Sat Nov 30 15:42:04 CST 2019
     */
    SysModel selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_model
     *
     * @mbg.generated Sat Nov 30 15:42:04 CST 2019
     */
    List<SysModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_model
     *
     * @mbg.generated Sat Nov 30 15:42:04 CST 2019
     */
    int updateByPrimaryKey(SysModel record);

    int checkByModelId(int modelId);
}